# Generated by Django 3.2.3 on 2023-05-11 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('requested_date', models.DateField()),
                ('requested_time', models.CharField(choices=[('18:00', '18:30'), ('18:30', '19:00'), ('19:00', '19:30'), ('19:30', '20:00'), ('20:00', '20:30')], default='18:00', max_length=30)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(default='', max_length=100)),
                ('status', models.CharField(choices=[('0', 'Confirmation pending'), ('1', 'Booking Confirmed')], default='Confirmation pending', max_length=25)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_time'],
            },
        ),
    ]
