# Generated by Django 3.2.3 on 2023-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[(0, 'Confirmation pending'), (1, 'Booking Confirmed')], default=0, max_length=25),
        ),
    ]
